<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />';
echo '';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Gestion de Formulaire avec TODO LIST</title>';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"';
echo 'integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">';
echo '';
echo '<link rel="stylesheet" href="style.css">';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="app">';
echo '<h4 class="mb-3">Gestion de Formulaire avec TODO LIST</h4>';
echo '';
echo '';
echo '<div id="addNew" data-bs-toggle="modal" data-bs-target="#form">';
echo '<span>Ajouter une Tâche</span>';
echo '<i class="fas fa-plus"></i>';
echo '</div>';
echo '';
echo '<!-- Modal -->';
echo '<form class="modal fade" id="form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<h5 class="modal-title" id="exampleModalLabel">Ajouter une Tâche</h5>';
echo '<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
echo '</div>';
echo '<div class="modal-body">';
echo '<p>Titre de la Tâche</p>';
echo '<input type="text" class="form-control" name="" id="textInput">';
echo '<div id="msg"></div>';
echo '<br>';
echo '<p>La Date Dû</p>';
echo '<input type="date" class="form-control" name="" id="dateInput">';
echo '<br>';
echo '<p>Description</p>';
echo '<textarea name="" class="form-control" id="textarea" cols="30" rows="5"></textarea>';
echo '</div>';
echo '<div class="modal-footer">';
echo '<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>';
echo '<button type="submit" id="add" class="btn btn-primary">Add</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '';
echo '<h5 class="text-center my-3">Les Tâches</h5>';
echo '';
echo '<div id="tasks">';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '<script src="main.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"';
echo 'integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>';
echo '</html>';
echo '';
?>